### ISSUE TITLE
follow user button is not responsive in mobile view

### ISSUE THREAD

**Issue by munsif12** [benawad/dogehouse#2483]
![IMG_20210502_030252](https://user-images.githubusercontent.com/53260498/116796041-ed00eb00-aaf2-11eb-8027-1b4bfcd3db8f.jpg)
![IMG_20210502_030450](https://user-images.githubusercontent.com/53260498/116796070-2d606900-aaf3-11eb-85b5-b43ed9fd1a8c.jpg)

**Comment by junedkhatri31** [comment]
What's the screen size of your mobile?

**Comment by munsif12** [comment]
> What's the screen size of your mobile?
@junedkhatri31 
It's 720 × 1544 pixels
And mobile is vivo y15

**Comment by amitojsingh366** [comment]
can you try a different browser?

**Comment by Alirezamxz** [comment]
Checked in 3 different browsers, i think it's ok
![bn](https://user-images.githubusercontent.com/47672255/116853177-dbab0200-ac0a-11eb-8687-f73ceb74eadb.jpg)

**Comment by amitojsingh366** [comment]
ok then since this issue is fixed ill close it

**Comment by munsif12** [comment]
> Checked in 3 different browsers, i think it's ok
> ![bn](https://user-images.githubusercontent.com/47672255/116853177-dbab0200-ac0a-11eb-8687-f73ceb74eadb.jpg)

@Alirezamxz Thanks brother

**Comment by munsif12** [comment]
@amitojsingh366 
@Alirezamxz 
@junedkhatri31 
Guys i am soory but i tested  the same issue again on 3 different browers  ( Google Chrome ,opera mini and firefox )but its still not working
I am attaching screenshot with browers name on them 
hoping the best 👍
![Screenshot_20210503_231543](https://user-images.githubusercontent.com/53260498/116916762-3114fc80-ac67-11eb-884b-1dd2a9aeb851.jpg)
![IMG_20210503_232135](https://user-images.githubusercontent.com/53260498/116916790-396d3780-ac67-11eb-962e-b398dcea7441.jpg)
![Screenshot_20210503_232007](https://user-images.githubusercontent.com/53260498/116916840-468a2680-ac67-11eb-852f-04f14143235d.jpg)
![Screenshot_20210503_231401](https://user-images.githubusercontent.com/53260498/116916881-543fac00-ac67-11eb-8783-8e4b19eff2b0.jpg)

**Comment by amitojsingh366** [comment]
oh this is still an issue? ok ill reopen this

**Comment by munsif12** [comment]
> oh this is still an issue? ok ill reopen this

Yes @amitojsingh366  this time i have tested it on 3 diff browers as you can see by the SS

**Comment by Alirezamxz** [comment]
@amitojsingh366 you closed my pr I changed two line and it works.
if you want please re check my pr changes

**Comment by amitojsingh366** [comment]
> 
> 
> @amitojsingh366 you closed my pr I changed two line and it works.
> if you want please re check my pr changes

sure, actually this issue was fixed for a while and it broke again. that's why i closed your pr

**Comment by munsif12** [comment]
> > @amitojsingh366 you closed my pr I changed two line and it works.
> > if you want please re check my pr changes
> 
> sure, actually this issue was fixed for a while and it broke again. that's why i closed your pr

Ok well

**Comment by munsif12** [comment]
@amitojsingh366 
@benawad 
@Alirezamxz 
@jhony-24 
![Screenshot_20210506_081456](https://user-images.githubusercontent.com/53260498/117237077-96254980-ae43-11eb-83b5-572b0419ff10.jpg)
Now this is looking very clean and beautiful 😍
Guys Thank you soo much for the hard work you put on to solve this issue I really appreciate  that 
Best of luck to Dogehouse  which is going to the moon 🚀
