### ISSUE TITLE
mute yourself, then unmute, then try talking and active speaker bubble doesn't always show right away

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#384]

**Comment by Delected** [comment]
![image](https://user-images.githubusercontent.com/58377193/109334832-38ff8d00-782f-11eb-99dd-09130f7e4b0c.png)
this ^^^
bubble is not showing up, just a visual bug so it's that important/severe

**Comment by benawad** [comment]
note to self: I'm not able to replicate this locally, might need to test it in prod.

Could be related to race condition

**Comment by benawad** [comment]
only for you

**Comment by Delected** [comment]
> 
> 
> only for you

I think it's solved now, I just tested it.

**Comment by jamesql** [comment]
I was able to get this to reproduce in 2 ways. (Windows, Chrome)

1) 
- Create a channel while muted.

2)  
- Create a channel
- Someone else is in the channel
- Mute and unmute

**Comment by wes337** [comment]
This is definitely still happening, was able to reproduce this last night. Investigating

**Comment by Delected** [comment]
> 
> 
> I was able to get this to reproduce in 2 ways. (Windows, Chrome)
> 
> 
>     * Create a channel while muted.
> 
> 
> 
>     * Create a channel
> 
>     * Someone else is in the channel
> 
>     * Mute and unmute



> 
> 
> This is definitely still happening, was able to reproduce this last night. Investigating

i see.. i had tested it without a friend in the channel (thus why my bubble was working properly). i'll see if he can get on, and test it again... my apologies

**Comment by jamesql** [comment]
@Delected @wes337 I got it to reproduce that night I left a comment but now it happens randomly, sometimes it works sometimes it does not.

**Comment by HarrisonMayotte** [comment]
I'm on the same page as @jamesql

**Comment by BronzW** [comment]
Still a problem on the new version?
